<a href="https://colab.research.google.com/github/pccalegari/exemplos-CN/blob/main/eqcalor2D_implicito.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

def phi(x, y, t):
  return np.exp(-t)*np.sin(np.pi*x)*np.sin(np.pi*y)

def f(x, y, t):
  return (2*np.pi*np.pi - 1)*np.exp(-t)*np.sin(np.pi*x)*np.sin(np.pi*y)

def main():
  N = 4
  b = 1.0
  a = 0.0
  h = (b - a)/N
  t0 = 0
  tf = 0.5
  dt = (h*h)/4

  x = np.zeros(N)
  y = np.zeros(N)
  
  x[0] = a + h/2
  y[0] = a + h/2
  for i in range(1,N): 
    x[i] = x[i-1] + h
    y[i] = y[i-1] + h

  
  phia = np.zeros((N+2,N+2))
  phie = np.zeros((N+2,N+2))
  phi0 = np.zeros((N+2,N+2))
  ff = np.zeros((N+2,N+2))
  r = np.zeros((N+2,N+2))

  for j in range(1,N+1):
    for i in range(1,N+1):
      phi0[i][j] = phi(x[i-1], y[j-1], t0) 
      phie[i][j] = phi(x[i-1], y[j-1], tf)

   
  
  #Preenchimento das fantasmas: Condiçao inicial
  for i in range(1,N+1):
    phi0[i][0] = 2*phi(x[i-1], a, t0) - phi0[i][1]
    phi0[i][N+1] = 2*phi(x[i-1], b, t0) - phi0[i][N]
    phi0[0][i] = 2*phi(a, y[i-1], t0) - phi0[1][i]
    phi0[N+1][i] = 2*phi(b, y[i-1], t0) - phi0[N][i]

  

#  t = t0
#  while (t < tf):
#    s = dt/(h*h)
     #Inicializacao do chute inicial
     # phi = 

#    t += dt
    #Solucao do sistema Gauss Seidel
    

    #Condição de contorno
#    b[0] = b[0] + s*phi(x[0],t)
#    b[N-2] = b[N-2] + s*phi(x[N],t)

    #solucao do sistema
#    phia = np.linalg.solve(A, b)

    #atualizaçao para o proximo instante de tempo
#    for i in range(N-1):
#      phi0[i] = phia[i]

    #calculo do tamanho do passo de tempo    
#    dt = min(dt, tf - t)

  #dados para o grafico
#  for i in range(N-1):
#    phiag[i+1] = phia[i]
#  phiag[0] = phi(x[0],t)
#  phiag[N] = phi(x[N],t) 

#  print("erro norma maximo", np.linalg.norm(phie - phia, ord=np.inf))  

#  plt.figure(1)
#  plt.plot(x[1:N], phia, 'o', label='tf=0.5')
#  plt.plot(x[1:N], phie, '*', label='exata')
#  plt.xlabel("x")
#  plt.legend()
#  plt.show()

main() 

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.14644661 0.35355339 0.35355339 0.14644661 0.        ]
 [0.         0.35355339 0.85355339 0.85355339 0.35355339 0.        ]
 [0.         0.35355339 0.85355339 0.85355339 0.35355339 0.        ]
 [0.         0.14644661 0.35355339 0.35355339 0.14644661 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]
[[ 0.         -0.14644661 -0.35355339 -0.35355339 -0.14644661  0.        ]
 [-0.14644661  0.14644661  0.35355339  0.35355339  0.14644661 -0.14644661]
 [-0.35355339  0.35355339  0.85355339  0.85355339  0.35355339 -0.35355339]
 [-0.35355339  0.35355339  0.85355339  0.85355339  0.35355339 -0.35355339]
 [-0.14644661  0.14644661  0.35355339  0.35355339  0.14644661 -0.14644661]
 [ 0.         -0.14644661 -0.35355339 -0.35355339 -0.14644661  0.        ]]


In [ ]:
print(0.15938636634155837/0.07896636818093875)
print(0.07896636818093875/0.039507848680057446)
print(0.039507848680057446/0.01979054335885396)

2.0184082162212413
1.9987514081170143
1.996299341745071
