<a href="https://colab.research.google.com/github/pccalegari/exemplos-CN/blob/main/unidade3_MetodosDiretos_aula2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Unidade 3 - Sistemas de equações

A seguir alguns exemplos, do método de eliminação de Gauss e fatoração LU, utilizando as bibliotecas [numpy](https://numpy.org/) e [scipy](https://scipy.github.io/devdocs/index.html).

**Exemplo 1:** Sistema triangular superior

$\displaystyle{\left\{\begin{array}{ccccccccc}
x_1 & + & x_2 &  &  & + & 3x_4 &= & 5 \\
  &  & 2x_2 & - & x_3 & + & x_4 & = & 2 \\
  & & & - & x_3 & + & 2x_4 & = & 1\\
 &  &  &  &  & - & 2x_4 & =  & -2\\
\end{array}\right .}$

Na forma matricial, $A{\bf x} = {\bf b}$, com

$\displaystyle{A=\left(\begin{array}{cccc}
1 & 1 & 0 & 3 \\
0 & 2 & -1 & 1 \\
0 & 0 & -1 & 2 \\
0 & 0 & 0 & -2 \\
\end{array}\right ), {\bf b} = \left(\begin{array}{c}
5 \\
2 \\
1 \\
-2 \\
\end{array}\right)}$

**Algoritmo:** Substituição inversa

Dados $A$ triangular superior, com $a_{ii}\neq 0$ e $b$.
1. $x_n = b_n/a_{nn}$
2. Para $i = n-1$ até $1$
3. $\hspace{1pc}$ soma = $b_i$
4. $\hspace{1pc}$ Para $j=i+1$ até $n$
5. $\hspace{2pc}$  soma $=$ soma $- a_{ij}x_j$
6. $\hspace{1pc}$  $x_k = \mbox{soma}/a_{ii}$



**Exemplo 2:** Sistema triangular inferior

$\displaystyle{\left\{\begin{array}{ccccccccc}
3x_1 &  &  &  &  &  &  &= & 5 \\
x_1  & - & 2x_2 &  &  &  &  & = & 1 \\
3x_1 & + & 3x_2 & - & x_3 & & & = & 5\\
x_1 & + & x_2 & - & x_3 & + & 3x_4 & =  & -2\\
\end{array}\right .}$

Na forma matricial, $A{\bf x} = {\bf b}$, com

$\displaystyle{A=\left(\begin{array}{cccc}
3 & 0 & 0 & 0 \\
1 & -2 & 0 & 0 \\
3 & 3 & -1 & 0 \\
1 & 1 & -1 & 3 \\
\end{array}\right ), {\bf b} = \left(\begin{array}{c}
5 \\
1 \\
5 \\
-2 \\
\end{array}\right)}$

**Algoritmo:** Substituição Direta

Dados $A$ triangular inferior, com $a_{ii}\neq 0$ e ${\bf b}$.
1. $x_1 = b_1/a_{11}$
2. Para $i = 2$ até $n$
3. $\hspace{1pc}$ soma = $b_i$
4. $\hspace{1pc}$ Para $j=i-1$ até $1$
5. $\hspace{2pc}$  soma $=$ soma $- a_{ij}x_j$
6. $\hspace{1pc}$  $x_k = \mbox{soma}/a_{ii}$




**Exemplo 3:**

$\displaystyle{\left\{\begin{array}{ccccccccc}
x_1 & + & 4x_2 & + & 52x_3 & = & 57 \\
27x_1 & + & 110x_2 & - & 3x_3 & = & 134 \\
22x_1 & + & 2x_2 & + & 14x_3 & =  & 38\\
\end{array}\right .}$

$\displaystyle{A=\left(\begin{array}{ccc}
1 & 4 & 52 \\
27 & 110 & -3 \\
22 & 2 & 14\\
\end{array}\right ), b = \left(\begin{array}{c}
57 \\
134 \\
38\\
\end{array}\right)}$


Eliminaçao de Gauss com pivoteamento, 4 algarismos significativos e corte.

Passo 1: troca de linhas $L_2 \sim L_1$.

Passo 2: $L_2\leftarrow L_2 - m_{21}L_1$ e $L_3\leftarrow L_3 - m_{31}L_1$, com $m_{21}=a_{21}/a_{11}$ e $m_{31}=a_{31}/a_{11}$. Neste caso, $m_{21}=1/27 \approx 0.03703$ e $m_{31}=a_{31}/a_{11}=22/27\approx 0.8148$. Note que estes multiplicadores, ficarão armazenados nas posições que foram anuladas, veja a primeira coluna da terceira matriz.

Operações na linha 2:

$4 - 0.03703\times 110 \approx 4 - 4.073 = -0.073,$

$52 - 0.03703\times (-3) \approx 52 + 0.1110 \approx 52.11,$

$57 - 0.03703\times 134 \approx 57 - 4.962\approx 52.03.$

Operações na linha 3:

$2 - 0.8148\times 110 \approx 2 - 89.62 \approx -87.62,$

$14 - 0.8148\times (-3) \approx 14 + 2.444 \approx 16.44,$

$38 - 0.8148\times 134 \approx 38 - 109.1 \approx -71.1.$

$\displaystyle{\left(\begin{array}{ccc|c}
1 & 4 & 52 & 57 \\
27 & 110 & -3 & 134 \\
22 & 2 & 14 & 38 \\
\end{array}\right ) \sim \left(\begin{array}{ccc|c}
27 & 110 & -3 & 134 \\
1 & 4 & 52 & 57 \\
22 & 2 & 14 & 38 \\
\end{array}\right)\sim \left(\begin{array}{ccc|c}
27 & 110 & -3 & 134 \\
0.03703 & -0.073 & 52.11 & 52.03 \\
 0.8148 & -87.62 & 16.44 & -71.1 \\
\end{array}\right )}$

Passo 3: $L_2\sim L_3$.

Passo 4: $L_3\leftarrow L_3 - m_{32}L_2$, com $m_{32}=a_{32}/a_{22}$. Neste caso, $\displaystyle{m_{32}=\dfrac{-0.073}{-87.62}\approx 0.0008331}$.

Operações na linha 3:

$52.11 - 0.0008331\times 16.44 \approx 52.11 - 0.01369 \approx 52.09,$

$52.03 - 0.0008331\times (-71.1) \approx 52.03 + 0.05923 \approx 52.08,$


$\displaystyle{\left(\begin{array}{ccc|c}
27 & 110 & -3 & 134 \\
0.8148 & -87.62 & 16.44 & -71.1 \\
0.03703 & -0.073 & 52.11 & 52.03 \\
\end{array}\right )\sim \left(\begin{array}{ccc|c}
27 & 110 & -3 & 134 \\
0.8148 & -87.63 & 16.44 & -71.1 \\
0.03703 & 0.0008331 & 52.09 & 52.08 \\
\end{array}\right)}$

Note que a última matriz contém o sistema de equações triangular superior equivalente (parte triangular superior) e na parte triangular inferior (abaixo da diagonal principal) temos os multiplicadores armazenados. Além disso, foram realizadas trocas de linha, $p_1=2$, ou seja, no passo 1 fizemos a troca $L_1\sim L_2$ e $p_2=3$, ou seja, no passo 3 foi feita a troca $L_2\sim L_3$.

O sistema triangular superior equivalente pode ser escrito na forma:

$\displaystyle{\left\{\begin{array}{ccccccccc}
27x_1 & + & 110x_2 & - & 3x_3 & = & 134 \\
      & -  & 87.62x_2 & + & 16.44x_3 & = & -71.1 \\
      &   &   &  & 52.09x_3 & =  & 52.08\\
\end{array}\right .}$

Resolvendo o sistema triangular equivalente, utilizando a substituição inversa, obtemos:

$\displaystyle{x_3 = \dfrac{52.08}{52.09}\approx 0.9998,}$

$\displaystyle{x_2 = \dfrac{-71.1 - 16.44\times 0.9998}{-87.63}\approx \dfrac{-71.1 - 16.43}{-87.62}\approx \dfrac{87.53}{87.62}\approx 0.9989,}$

$\displaystyle{x_3 = \dfrac{134 - 110\times 0.9989 + 3\times 0.9998}{27}\approx \dfrac{134 - 109.8 + 2.999}{27}\approx \dfrac{24.2 + 2.999}{27} \approx \dfrac{27.19}{27}\approx 1.007.}$

Assim, ${\bf x}=(1.007, 0.9989, 0.9998)$.

**Fatoração LU**

A partir do método da Eliminação de Gauss podemos obter a fatoração: $A=LU$, onde a matriz $L$ é uma matriz triangular inferior que contém $1$ na diagonal e os multiplicadores (da eliminação de Gauss) abaixo da diagonal e a matriz $U$ é triangular superior e é a matriz equivalente a matriz $A$ resultante do método de Eliminação de Gauss.
      
Note que se $A = LU$ então o sistema linear $A{\bf x} = b$ pode ser reescrito como dois sistemas triangulares:

$$A{\bf x} = (LU){\bf x} = L(U{\bf x}) = {\bf b}.$$

Se chamarmos $U{\bf x} = {\bf y}$, obtemos dois sistemas triangulares: $L{\bf y} = {\bf b}$ e $U{\bf x} = {\bf y}$.

Dessa forma podemos resolver $2$ sistemas lineares triangulares: $L{\bf y} = {\bf b}$ (triangular inferior) e $U{\bf x} = {\bf y}$ (triangular superior).

Usaremos o método da substituição direta para resolver o sistema triangular inferior e o método da substituição inversa, para o triangular superior.

*Vantagem:* Quando precisamos resolver diversos sistemas lineares onde apenas o lado direito ${\bf b}$ muda. Exemplo: A técnica de refinamento de solução, que veremos em breve.

**Exemplo 4:** Vamos utilizar a função lu do módulo *scipy*.

Do exemplo anterior, após aplicar o Método da Eliminação Gaussiana, obtemos:

$\displaystyle{\left(\begin{array}{ccc|c}
27 & 110 & -3 & 134 \\
0.8148 & -87.62 & 16.44 & -71.1 \\
 0.03703 & 0.0008331 & 52.09 & 52.08 \\
\end{array}\right )}$

Como extrair a fatoração $LU$?

$\displaystyle{U = \left(\begin{array}{ccc}
27 & 110 & -3 \\
0 & -87.62 & 16.44 \\
 0 & 0 & 52.09  \\
\end{array}\right )}$ e $\displaystyle{L = \left(\begin{array}{ccc}
1 & 0 & 0 \\
0.8148 & 1 & 0 \\
 0.03703 & 0.0008331 & 1  \\
\end{array}\right )}$

Note que, o produto das matrizes LU fornece a matriz A com as linhas trocadas. A matriz $P$ devolvida pela função lu armazena as trocas de linhas (matriz de permutação) que ocorreram durante o método de eliminação de Gauss. Uma matriz de permutação é a matriz identidade com as linhas trocadas. Neste caso, a $P$ devolvida, satisfaz $A = PLU$.



In [13]:
import numpy as np
import scipy as sp

#U = np.array([[27, 110, -3], [0, -87.62, 16.44], [0, 0, 52.09]])
#L = np.array([[1, 0, 0], [0.8148, 1, 0], [0.03703, 0.0008331, 1]])
A = np.array([[1, 4, 52], [27, 110, -3], [22, 2, 14]])
P, L, U = sp.linalg.lu(A)

print("L = ", L)
print("U = ", U)
print("P = ", P )
A = np.dot(L, U)
print(A)

L =  [[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.14814815e-01 1.00000000e+00 0.00000000e+00]
 [3.70370370e-02 8.45308538e-04 1.00000000e+00]]
U =  [[ 27.         110.          -3.        ]
 [  0.         -87.62962963  16.44444444]
 [  0.           0.          52.09721048]]
P =  [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[ 27. 110.  -3.]
 [ 22.   2.  14.]
 [  1.   4.  52.]]


**Exemplo 5:**

$\displaystyle{A=\left(\begin{array}{cccc}
1 & 1 & 0 & 3 \\
2 & 1 & -1 & 1 \\
3 & -1 & -1 & 2 \\
-1 & 2 & 3 & -1 \\
\end{array}\right ), b_1 = \left(\begin{array}{c}
1 \\
1 \\
-3 \\
4 \\
\end{array}\right), b_2 = \left(\begin{array}{c}
8 \\
7 \\
14 \\
-7 \\
\end{array}\right)}$

Eliminaçao de Gauss com condensaçao pivotal, 4 algarismos significativos e arredondamento.

Passo 1: troca de linhas $L_3 \sim L_1$.

Passo 2: $L_2\leftarrow L_2 - (2/3)L_1$, $L_3\leftarrow L_3 - (1/3)L_1$ e $L_4\leftarrow L_4 + (1/3)L_1$.

Linha 2:

$1 - 0.6667\times (-1) \approx 1.667 $

$-1 -0.6667\times (-1) \approx -1 + 0.6667 \approx -0.3333 $

$1 -0.6667\times 2 \approx 1 - 1.333 \approx -0.3333$

Linha 3:

$1 - 0.3333\times (-1) \approx 1.333 $

$0 -0.3333\times (-1) \approx 0.3333 $

$3 -0.3333\times 2 \approx 3 - 0.6666 \approx 2.333$


Linha 4:

$2 + 0.3333\times (-1) \approx 1.667 $

$3 +0.3333\times (-1) \approx 2.667 $

$-1 + 0.3333\times 2 \approx -1 + 0.6666 \approx -0.3334$

$\displaystyle{\left(\begin{array}{cccc}
1 & 1 & 0 & 3 \\
2 & 1 & -1 & 1 \\
3 & -1 & -1 & 2 \\
-1 & 2 & 3 & -1 \\
\end{array}\right ) \sim \left(\begin{array}{cccc}
3 & -1 & -1 & 2 \\
2 & 1 & -1 & 1 \\
1 & 1 & 0 & 3 \\
-1 & 2 & 3 & -1 \\
\end{array}\right)\sim \left(\begin{array}{cccc}
3 & -1 & -1 & 2 \\
0.6667 & 1.667 & -0.3333 & -0.3333 \\
0.3333 & 1.333 & 0.3333 & 2.333 \\
-0.3333 & 1.667 & 2.667 & -0.3334 \\
\end{array}\right )}$

Passo 3: $L_3\leftarrow L_3 - (1.333/1.667)L_2$ e $L_4\leftarrow L_4 - L_2$.

Linha 3:

$0.3333 -0.7996\times (-0.3333) \approx 0.3333 + 0.2665 \approx 0.5998$

$2.333 -0.7996\times (-0.3333) \approx 2.333 + 0.2665 \approx 2.6$

Linha 4:

$2.667 - 1\times (-0.3333) \approx 2.667 + 0.3333 \approx 3$

$-0.3334 -1\times (-0.3333) \approx -0.0001 $

Passo 4: $L_3\sim L_4$.

Passo 5: $L_4\leftarrow L_4 - (0.5998/3)L_2$.

Linha 4:

$2.6 - 0.1999\times (-0.0001) \approx 2.6 + 0.00001999 \approx 2.6$

$\displaystyle{\left(\begin{array}{cccc}
3 & -1 & -1 & 2 \\
0.6667 & 1.667 & -0.3333 & -0.3333 \\
0.3333 & 0.7996 & 0.5998 & 2.6\\
-0.3333 & 1 & 3 & -0.0001 \\
\end{array}\right )\sim \left(\begin{array}{cccc}
3 & -1 & -1 & 2 \\
0.6667 & 1.667 & -0.3333 & -0.3333\\
-0.3333 & 1 & 3 & -0.0001 \\
0.3333 & 0.7996 & 0.5998 & 2.6\\
\end{array}\right) }$

$\displaystyle{\sim \left(\begin{array}{cccc}
3 & -1 & -1 & 2 \\
0.6667 & 1.667 & -0.3333 & -0.3333 \\
-0.3333 & 1 & 3 & -0.0001 \\
0.3333 & 0.7996 & 0.1999 & 2.6\\
\end{array}\right)}$

Note que a matriz $P$ que representa as trocas de linha é a permutação da matriz identidade: $L_1\sim L_3$ e $L_3\sim L_4$. Ou seja,

$\displaystyle{P = \left(\begin{array}{cccc}
0 & 0 & 1 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 0 & 1\\
1 & 0 & 0 & 0\\
\end{array}\right )}$

 Assim temos $PA = LU$, com

$\displaystyle{L = \left(\begin{array}{cccc}
1 & 0 & 0 & 0 \\
0.6667 & 1 & 0 & 0 \\
-0.3333 & 1 & 1 & 0 \\
0.3333 & 0.7996 & 0.1999 & 1\\
\end{array}\right )}$ e $\displaystyle{U = \left(\begin{array}{cccc}
3 & -1 & -1 & 2 \\
0 & 1.667 & -0.3333 & -0.3333 \\
0 & 0 & 3 & -0.0001 \\
0 & 0 & 0 & 2.6\\
\end{array}\right )}$

Dessa forma, para resolver o sistema, precisamos fazer as trocas de linhas no vetor b. Isso é feito multiplicando $Ax=b$ pela matriz de permutaçao $PA{\bf x} = P{\bf b}$.

Usando a fatoraçao LU, iremos resolver o sistema $PA{\bf x} = P{\bf b}$:

$\displaystyle{\left(\begin{array}{cccc}
3 & -1 & -1 & 2 \\
1 & 1 & 0 & 3 \\
-1 & 2 & 3 & -1 \\
2 & 1 & -1 & 1 \\
\end{array}\right )\left(\begin{array}{c}
x_1 \\
x_2 \\
x_3 \\
x_4 \\
\end{array}\right) = \left(\begin{array}{c}
-3 \\
1 \\
4 \\
1 \\
\end{array}\right)}$

Os sistemas triangulares, resultantes da decomposição LU são:

$L{\bf y} = {\bf b}$

$\displaystyle{\left(\begin{array}{cccc}
1 & 0 & 0 & 0 \\
0.6667 & 1 & 0 & 0 \\
-0.3333 & 1 & 1 & 0 \\
0.3333 & 0.7996 & 0.1999 & 1\\
\end{array}\right )\left(\begin{array}{c}
y_1 \\
y_2 \\
y_3 \\
y_4 \\
\end{array}\right) = \left(\begin{array}{c}
-3 \\
1 \\
4 \\
1 \\
\end{array}\right)}$

Resolvendo o sistema triangular superior:

$y_1 = -3$,

$y_2=1-0.6667y_1 \approx 1+2 \Rightarrow y_2\approx 3$,

$y_3=4-y_2+0.3333y_1\approx 4-3-0.9999\Rightarrow y_3\approx 0.0001,$

$y_4=1-0.1999y_3-0.7996y_2 -0.3333y_1\approx 1-0.00001999-2.399+0.9999\Rightarrow y_4=-0.3991.$

$U{\bf x} = {\bf y}$

$\displaystyle{\left(\begin{array}{cccc}
3 & -1 & -1 & 2 \\
0 & 1.667 & -0.3333 & -0.3333 \\
0 & 0 & 3 & -0.0001 \\
0 & 0 & 0 & 2.6\\
\end{array}\right )\left(\begin{array}{c}
x_1 \\
x_2 \\
x_3 \\
x_4 \\
\end{array}\right) = \left(\begin{array}{c}
-3 \\
3 \\
0.0001 \\
-0.3991 \\
\end{array}\right)}$

Resolvendo o sistema triangular superior:

$x_4 = -0.3991/2.6 \Rightarrow x_4 = -0.1535$,

$x_3=(0.0001 + 0.0001x_4)/3  \approx (0.0001 - 0.00001535)/3 \approx 0.00008465/3 \Rightarrow x_3 = 0.00002822$,

$x_2=(3+0.3333x_3+0.3333x_4)/1.667\approx (3 + 0.00002822 - 0.05116)/1.667  \approx 2.949/1.667 \Rightarrow x_2= 1.769,$

$x_1=(-3 -2x_4+x_3 +x_2)/3 \approx (-3 + 0.307 + 0.00002822 + 1.769)/3 \approx -0.924/3 \Rightarrow x_1= -0.308.$

Portanto, a solução aproximada do sistema é ${\bf x} = (-0.308, 1.769, 0.00002822, -0.1535)$.

In [18]:
import numpy as np
import scipy as sp


A = np.array([[1, 1, 0, 3], [2, 1, -1, 1], [3, -1, -1, 2], [-1, 2, 3, -1]])
b = np.array([1,1,-3,4])
