<a href="https://colab.research.google.com/github/pccalegari/exemplos-CN/blob/main/unidade3-MetodosDiretos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Unidade 3 - Sistemas de equações

A seguir alguns exemplos, do método de eliminação de Gauss e fatoração LU, utilizando as bibliotecas [numpy](https://numpy.org/) e [scipy](https://scipy.github.io/devdocs/index.html).

**Exemplo 1: Sistema triangular superior**

$\displaystyle{A=\left(\begin{array}{cccc}
1 & 1 & 0 & 3 \\
0 & 2 & -1 & 1 \\
0 & 0 & -1 & 2 \\
0 & 0 & 0 & -2 \\
\end{array}\right ), b = \left(\begin{array}{c}
5 \\
2 \\
1 \\
-2 \\
\end{array}\right)}$

Algoritmo:

Dados $A$ com $a_{ii}\neq 0$.
1. $x_n = b_n/a_{nn}$
2. $\mbox{soma} = 0$
3. Para $k = n-1$ até $1$
4. $\hspace{1pc}$ soma = $b_k$
5. $\hspace{1pc}$ Para $j=k+1$ até $n$
6. $\hspace{2pc}$  soma $=$ soma $- a_{kj}x_j$
7. $\hspace{1pc}$  $x_k = \mbox{soma}/a_{kk}$




**Exemplo 2:**

$\displaystyle{A=\left(\begin{array}{ccc}
1 & 4 & 52 \\
27 & 110 & -3 \\
22 & 2 & 14\\
\end{array}\right ), b = \left(\begin{array}{c}
57 \\
134 \\
38\\
\end{array}\right)}$


Eliminaçao de Gauss com condensaçao pivotal e 4 algarismos significativos.

Passo 1: troca de linhas $L_2 \sim L_1$. Passo 2: $L_2\leftarrow L_2 - (1/27)L_1$ e $L_3\leftarrow L_3 - (22/27)L_1$.

$\displaystyle{\left(\begin{array}{ccc|c}
1 & 4 & 52 & 57 \\
27 & 110 & -3 & 134 \\
22 & 2 & 14 & 38 \\
\end{array}\right ) \sim \left(\begin{array}{ccc|c}
27 & 110 & -3 & 134 \\
1 & 4 & 52 & 57 \\
22 & 2 & 14 & 38 \\
\end{array}\right)\sim \left(\begin{array}{ccc|c}
27 & 110 & -3 & 134 \\
0.03704 & -0.0744 & 52.11 & 52.04 \\
 0.8148 & -87.63 & 16.44 & -71.2 \\
\end{array}\right )}$

Passo 3: $L_2\sim L_3$. Passo 4: $L_3\leftarrow L_3 - (0.0744/87.63)L_1$.

$\displaystyle{\left(\begin{array}{ccc|c}
27 & 110 & -3 & 134 \\
0.8148 & -87.63 & 16.44 & -71.2 \\
0.03704 & -0.0744 & 52.11 & 52.04 \\
\end{array}\right )\sim \left(\begin{array}{ccc|c}
27 & 110 & -3 & 134 \\
0.8148 & -87.63 & 16.44 & -71.2 \\
0.03704 & 0.000849 & 52.1 & 52.1 \\
\end{array}\right)}$

Note que a última matriz contém a matriz U (parte triangular superior) e a matriz L (multiplicadores, abaixo da diagonal principal). A matriz P é uma permultaçao da matriz identidade (mesmas trocas de linhas realizadas durante o processo).

$\displaystyle{P = \left(\begin{array}{ccc}
0 & 0 & 1 \\
1 & 0 & 0 \\
0 & 1 & 0 \\
\end{array}\right ), L = \left(\begin{array}{ccc}
1 & 0 & 0 \\
0.8148 & 1 & 0 \\
0.03704 & 0.000849 & 1 \\
\end{array}\right), U= \left(\begin{array}{ccc}
27 & 110 & -3 \\
0 & -87.63 & 16.44 \\
0 & 0 & 52.1 \\
\end{array}\right )}$


In [ ]:
from scipy.linalg import lu

A = np.array([[1, 4, 52], [27, 110, -3], [22, 2, 14]])
b = np.array([57, 134, 38])

p, l, u = lu(A)

print('L = ', l)

print('U = ', u)

print('P = ', p)

x1 = np.linalg.solve(A, b)
print('x = ', x1)
print(np.linalg.cond(A))

L =  [[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.14814815e-01 1.00000000e+00 0.00000000e+00]
 [3.70370370e-02 8.45308538e-04 1.00000000e+00]]
U =  [[ 27.         110.          -3.        ]
 [  0.         -87.62962963  16.44444444]
 [  0.           0.          52.09721048]]
P =  [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
x =  [1. 1. 1.]
5.677574276033183


**Exemplo 3:**

$\displaystyle{A=\left(\begin{array}{cccc}
1 & 1 & 0 & 3 \\
2 & 1 & -1 & 1 \\
3 & -1 & -1 & 2 \\
-1 & 2 & 3 & -1 \\
\end{array}\right ), b_1 = \left(\begin{array}{c}
1 \\
1 \\
-3 \\
4 \\
\end{array}\right), b_2 = \left(\begin{array}{c}
8 \\
7 \\
14 \\
-7 \\
\end{array}\right)}$

Eliminaçao de Gauss com condensaçao pivotal e 4 algarismos significativos.

Passo 1: troca de linhas $L_3 \sim L_1$. Passo 2: $L_2\leftarrow L_2 - (2/3)L_1$, $L_3\leftarrow L_3 - (1/3)L_1$ e $L_4\leftarrow L_4 + (1/3)L_1$.

$\displaystyle{\left(\begin{array}{cccc}
1 & 1 & 0 & 3 \\
2 & 1 & -1 & 1 \\
3 & -1 & -1 & 2 \\
-1 & 2 & 3 & -1 \\
\end{array}\right ) \sim \left(\begin{array}{cccc}
3 & -1 & -1 & 2 \\
2 & 1 & -1 & 1 \\
1 & 1 & 0 & 3 \\
-1 & 2 & 3 & -1 \\
\end{array}\right)\sim \left(\begin{array}{cccc}
3 & -1 & -1 & 2 \\
0.6667 & 1.667 & -0.3333 & -0.3333 \\
0.3333 & 1.333 & 0.3333 & 2.333 \\
-0.3333 & 1.667 & 2.667 & -0.3333 \\
\end{array}\right )}$

Passo 3: $L_3\leftarrow L_3 - (1.333/1.667)L_2$ e $L_4\leftarrow L_4 - L_2$. Passo 4: $L_3\sim L_4$.

$\displaystyle{\left(\begin{array}{cccc}
3 & -1 & -1 & 2 \\
0.6667 & 1.667 & -0.3333 & -0.3333 \\
0.3333 & 0.7996 & 0.5998 & 2.6\\
-0.3333 & 1 & 3 & 0 \\
\end{array}\right )\sim \left(\begin{array}{cccc}
3 & -1 & -1 & 2 \\
0.6667 & 1.667 & -0.3333 & -0.3333\\
-0.3333 & 1 & 3 & 0 \\
0.3333 & 0.7996 & 0.5998 & 2.6\\
\end{array}\right)}$

Passo 5: $L_4\leftarrow L_4 - (0.5998/3)L_2$.

$\displaystyle{\left(\begin{array}{cccc}
3 & -1 & -1 & 2 \\
0.6667 & 1.667 & -0.3333 & -0.3333 \\
-0.3333 & 1 & 3 & 0 \\
0.3333 & 0.7996 & 0.1999 & 2.6\\
\end{array}\right)}$

Note que para resolver o sistema, precisamos fazer as trocas de linhas no vetor b. Isso é feito multiplicando $Ax=b$ pela matriz de permutaçao inversa (nesse caso, a transposta).

$\displaystyle{P = \left(\begin{array}{cccc}
0 & 0 & 1 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 0 & 1\\
1 & 0 & 0 & 0\\
\end{array}\right ), P^{T} = \left(\begin{array}{cccc}
0 & 0 & 0 & 1\\
0 & 1 & 0 & 0\\
1 & 0 & 0 & 0\\
0 & 0 & 1 & 0\\
\end{array}\right )}$.

Usando a fatoraçao LU, iremos resolver o sistema $P^{T}Ax = P^{T}b$:

$\displaystyle{\left(\begin{array}{cccc}
3 & -1 & -1 & 2 \\
1 & 1 & 0 & 3 \\
-1 & 2 & 3 & -1 \\
2 & 1 & -1 & 1 \\
\end{array}\right )\left(\begin{array}{c}
x_1 \\
x_2 \\
x_3 \\
x_4 \\
\end{array}\right) = \left(\begin{array}{c}
-3 \\
1 \\
4 \\
1 \\
\end{array}\right)}$

Sistemas triangulares:

$Ly = b$

$\displaystyle{\left(\begin{array}{cccc}
1 & 0 & 0 & 0 \\
0.6667 & 1 & 0 & 0 \\
-0.3333 & 1 & 1 & 0 \\
0.3333 & 0.7996 & 0.1999 & 1\\
\end{array}\right )\left(\begin{array}{c}
y_1 \\
y_2 \\
y_3 \\
y_4 \\
\end{array}\right) = \left(\begin{array}{c}
-3 \\
1 \\
4 \\
1 \\
\end{array}\right)}$

Resolvendo o sistema triangular superior:

$y_1 = -3$,

$y_2=1-0.6667y_1 \Rightarrow y_2=1+2\Rightarrow y_2=3$,

$y_3=4-y_2+0.3333y_1\Rightarrow y_3=4-3-0.9999\Rightarrow y_3=0.0001,$

$y_4=1-0.1999y_3-0.7996y_2 -0.3333y_1\Rightarrow y_4=1-0.00001999-2.399+0.9999\Rightarrow y_4=-0.3991.$

$Ux = y$

$\displaystyle{\left(\begin{array}{cccc}
3 & -1 & -1 & 2 \\
0 & 1.667 & -0.3333 & -0.3332 \\
0 & 0 & 3 & 0 \\
0 & 0 & 0 & 2.6\\
\end{array}\right )\left(\begin{array}{c}
x_1 \\
x_2 \\
x_3 \\
x_4 \\
\end{array}\right) = \left(\begin{array}{c}
-3 \\
3 \\
0.0001 \\
-0.3991 \\
\end{array}\right)}$

Resolvendo o sistema triangular superior:

$x_4 = -0.3991/2.6 \Rightarrow x_4 = -0.1535$,

$x_3=0.0001/3 \Rightarrow x_3=0.00003333$,

$x_2=(3+0.3333x_3+0.3333x_4)/1.667\Rightarrow x_2=2.949/1.667\Rightarrow x_2=1.769,$

$x_1=(-3 -2x_4+x_3 +x_2)/3\Rightarrow x_1=-3+0.307+0.00003333+1.769\Rightarrow x_1=-0.308.$

In [ ]:
from scipy.linalg import lu

A = np.array([[1, 1, 0, 3], [2, 1, -1, 1], [3, -1, -1, 2], [-1, 2, 3, -1]])
b = np.array([1, 1, -3, 4])

p, l, u = lu(A)
#P matriz permutaçao: trocas de linhas realizadas
print('P = ', p)
#Matriz L: contém os multiplicadores da eliminaçao de Gauss
print('L = ', l)
#Matriz u: matriz triangular superior obtida na eliminaçao de Gauss
print('U = ', u)
# Matriz LU é a matriz A com as linhas trocadas, pois A = PLU
print(l.dot(u))
# Matriz A
print('A = ', A)

#Para resolver um sistema Ax = b, com a matriz já fatorada:
# P^TA = LU(P^T b), pois as trocas de linhas feitas em A devem ser feitas em b
# Note que usamos P transposta no lugar da inversa. Isso ocorre, pois para
# matrizes de permutaçao transposta e igual a inversa
pt = np.transpose(p)
#soluçao do sistema triangular inferior
y = np.linalg.solve(l, pt.dot(b))
#print(y)
#soluçao do sistema triangular superior
x = np.linalg.solve(u, y)
print('x =', x)

#soluçao direta
x1 = np.linalg.solve(A, b)
print('x1 = ', x1)
#Para conferir a soluçao: Ax = b
print(A.dot(x1))
print(A.dot(x))


P =  [[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
L =  [[ 1.          0.          0.          0.        ]
 [-0.33333333  1.          0.          0.        ]
 [ 0.66666667  1.          1.          0.        ]
 [ 0.33333333  0.8         0.6         1.        ]]
U =  [[ 3.         -1.         -1.          2.        ]
 [ 0.          1.66666667  2.66666667 -0.33333333]
 [ 0.          0.         -3.          0.        ]
 [ 0.          0.          0.          2.6       ]]
[[ 3.00000000e+00 -1.00000000e+00 -1.00000000e+00  2.00000000e+00]
 [-1.00000000e+00  2.00000000e+00  3.00000000e+00 -1.00000000e+00]
 [ 2.00000000e+00  1.00000000e+00 -1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00  1.55431223e-16  3.00000000e+00]]
A =  [[ 1  1  0  3]
 [ 2  1 -1  1]
 [ 3 -1 -1  2]
 [-1  2  3 -1]]
x = [-3.07692308e-01  1.76923077e+00 -1.48029737e-16 -1.53846154e-01]
x1 =  [-3.07692308e-01  1.76923077e+00 -1.48029737e-16 -1.53846154e-01]
[ 1.  1. -3.  4.]
[ 1.  1. -3.  4.]


In [ ]:
A = np.array([[1, 0.98], [1, 1]])
b = np.array([4.95, 5])
x = np.linalg.solve(A, b)
print(x)
B = np.array([[1, 0.99], [1, 1]])
x = np.linalg.solve(B, b)
print(x)
print(np.linalg.cond(A))
print(np.linalg.cond(B))
Ainv = np.linalg.inv(A)


[2.5 2.5]
[2.22044605e-14 5.00000000e+00]
198.01494987625688
398.0074874844577
198.0199999999998
[[ 50. -49.]
 [-50.  50.]]
