<a href="https://colab.research.google.com/github/pccalegari/exemplos-CN/blob/main/unidade3a1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>





# Unidade 3 - Sistemas de equações




Nesta unidade, vamos estudar métodos diretos e iterativos para aproximar a solução se sistemas de equações lineares e métodos iterativos para sistemas de equações não lineares. A seguir, apresentamos alguns exemplos de resolução em *Python*. Vamos utilizar as bibliotecas [numpy](https://numpy.org/) e [scipy](https://scipy.github.io/devdocs/index.html).

# Método direto



Resolva os sistemas lineares abaixo usando o método de Eliminação de Gauss e Decomposição LU:    

(1) $$\begin{array}{rcl}
7x_1 + 2x_2-5x_3 & = & -18\\  
x_1 + 5x_2 -3x_3 & = & -40 \\  
2x_1-x_2-9x_3 & = & -26
\end{array}$$

(2) Programe os métodos para resolver $Ax = b$ onde, $$A_{ij}=\dfrac{1}{i+j-1}, b_i=\dfrac{1}{i}, i,j=1:n$$
Use $n=20,50$ e $100$. Você pode explicar seus resultados? Note que a solução exata é $(1,0,\ldots, 0)$.

(3) Considere o sistema:    
$$\begin{array}{rcl}
-2(1+h^2)x_1+x_2 & = & 1\\   
x_{i-1} - 2(1+h^2)x_i+x_{i+1} &=& 0, \ i=2:n-1\\ 
x_{n-1} - 2(1+h^2)x_n &= &1
\end{array}$$

(a) Use o algoritmo para matrizes tridiagonais e resolva o problema com $n=3$ e $h=0.1$.

(b) Programe o algoritmo para matriz triadiagonal e resolva o problema com $n=30$ e $h=0.1$.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import linalg
from time import time

A = np.array([[-1, -2.3, 4.7, 12], [-1.1, 2, 3.1,3.9], [-2.1, -2.2, 3.7, 16], [-1.2, 2.1, -1.1, 4]])
b = np.array([[4], [3.9], [12.2], [6]])

start_time = time()
x = linalg.inv(A).dot(b) 
print("tempo inversa: ", time() - start_time)

start_time = time()
x1 = np.linalg.solve(A, b)  
print("tempo eliminação Gauss: ", time() - start_time)


tempo inversa:  0.013547420501708984
tempo eliminação Gauss:  0.0012373924255371094


Decomposição LU, usando a biblioteca *scipy*. A função LU devolve as matrizes $P$ (Permutação), $L$ (triangular inferior) e $U$ (triangular superior). 

Exemplo: $$A = \left (\begin{array}{ccc}
1 & 4 & 52 \\
27 & 110 & -3 \\
22 & 2 & 14 \\
\end{array}\right )$$

In [10]:
import numpy as np
from scipy.linalg import lu

A = np.array([[1, 4, 52], [27, 110, -3], [22, 2, 14]])

p, l, u = lu(A)

np.allclose(A - p@l@u, np.zeros((3,3)))

print(l)

print(u)

print(p)

[[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.14814815e-01 1.00000000e+00 0.00000000e+00]
 [3.70370370e-02 8.45308538e-04 1.00000000e+00]]
[[ 27.         110.          -3.        ]
 [  0.         -87.62962963  16.44444444]
 [  0.           0.          52.09721048]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


# Métodos iterativos


Método de Jacobi e método de Gauss-Seidel

(4) Faça três iterações dos métodos de Gauss-Seidel e Jacobi para resolver o sistema:    

$$\begin{array}{rcl}
4x_1+0.24x_2+0.08x_3 &=& 8\\ 
0.09x_1+3x_2-0.15x_3 & = & 9\\ 
0.04x_1-0.08x_2+4x_3 & = & 20
\end{array}$$

Utilize $x^{0}=(0,0,0)$ e analise $\max_{i}|x_i^k - x_i^{k-1}|$ a cada iteração.

